# http://chrisstump.online/2016/02/20/docker-existing-rails-application/
version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379"
    # TODO volumes

  db:
    image: postgres:9.5
    ports:
      - "5432"
    # TODO volumes

  api:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
      - redis
    env_file: ./.prod.env
    command: puma -C config/puma.rb

  sidekiq:
    build: .
    links:
      - db
      - redis
    env_file: ./.prod.env
    command: sidekiq